name: Build and Release Flutter APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x' # Or use 'any'
          channel: 'stable'

      - name: Generate Android Project
        run: |
          flutter create --platforms=android .
          sed -i 's/flutter.minSdkVersion/23/g' android/app/build.gradle
          find android -type f -exec sed -i 's/1.7.10/1.9.22/g' {} +
          find android -type f -exec sed -i 's/1.7.1/1.9.22/g' {} +
          mkdir -p android/app/src/main/res/drawable
          cp android/app/src/main/res/mipmap-mdpi/ic_launcher.png android/app/src/main/res/drawable/ic_bg_service_small.png
          sed -i '/<application/a \        <service android:name="id.flutter.flutter_background_service.BackgroundService" android:foregroundServiceType="location" />' android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest /a \    <uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>\n    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>\n    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>\n    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION"/>\n    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n    <uses-permission android:name="android.permission.WAKE_LOCK"/>' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        id: build_apk
        run: flutter build apk --release

      - name: Rename APK
        working-directory: rwae3_mobile
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/mandoob_app.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mandoob_app
          path: rwae3_mobile/build/app/outputs/flutter-apk/mandoob_app.apk
